# Generated by Django 6.0.4 on 2026-04-25 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('stock', models.IntegerField(default=0)),
                ('shipping', models.CharField(blank=True, choices=[('available', 'شحن متوفر'), ('local', 'شحن جزئي'), ('not_available', 'شحن غير متوفر')], max_length=20)),
                ('wilaya', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('residence', models.CharField(choices=[('1', 'إقامة 1'), ('2', 'إقامة 2'), ('3', 'إقامة 3'), ('outside', 'خارج الإقامة')], default='1', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
